package asterisk

import (
	"database/sql"
	"fmt"
	"os"
	"strings"

	"github.com/wbergg/asterisk-extention-manager/internal/config"
	"github.com/wbergg/asterisk-extention-manager/internal/models"
)

func GenerateConfig(db *sql.DB) (string, error) {
	exts, err := models.ListAllExtensions(db)
	if err != nil {
		return "", fmt.Errorf("list extensions: %w", err)
	}

	var b strings.Builder
	b.WriteString("; Auto-generated by Asterisk Extension Manager — DO NOT EDIT\n\n")

	for _, ext := range exts {
		if ext.DirectoryOnly {
			continue
		}

		name := fmt.Sprintf("%d", ext.Extension)
		callerid := ext.CallerID
		if callerid == "" {
			callerid = name
		}

		fmt.Fprintf(&b, ";=============================================================================\n")
		fmt.Fprintf(&b, "; Extension %s - %s\n", name, callerid)
		fmt.Fprintf(&b, ";=============================================================================\n")

		fmt.Fprintf(&b, "[%s](endpoint-basic)\n", name)
		fmt.Fprintf(&b, "auth=auth%s\n", name)
		fmt.Fprintf(&b, "aors=%s\n", name)
		fmt.Fprintf(&b, "callerid=%s <%s>\n", callerid, name)
		b.WriteString("\n")

		fmt.Fprintf(&b, "[auth%s](auth-userpass)\n", name)
		fmt.Fprintf(&b, "username=%s\n", ext.SIPUsername)
		fmt.Fprintf(&b, "password=%s\n", ext.SIPPassword)
		b.WriteString("\n")

		fmt.Fprintf(&b, "[%s](aor-single)\n", name)
		b.WriteString("\n")
	}

	return b.String(), nil
}

func WriteConfig(db *sql.DB, cfg *config.Config) error {
	content, err := GenerateConfig(db)
	if err != nil {
		return err
	}

	tmpPath := cfg.PJSIPConfPath + ".tmp"
	if err := os.WriteFile(tmpPath, []byte(content), 0644); err != nil {
		return fmt.Errorf("write tmp config: %w", err)
	}

	if err := os.Rename(tmpPath, cfg.PJSIPConfPath); err != nil {
		return fmt.Errorf("rename config: %w", err)
	}

	return nil
}
