CREATE TABLE blocked_extensions (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    extension INTEGER NOT NULL UNIQUE,
    reason TEXT NOT NULL DEFAULT '',
    created_at DATETIME DEFAULT CURRENT_TIMESTAMP
);
